---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authzproxy-sia
    envs:
      - athenz-sia/athenz-sia.env
  - name: authzproxy-envoy
    files:
      - config.yaml=envoy/config.yaml
      - identity_sds.yaml=envoy/identity_sds.yaml
      - ca_sds.yaml=envoy/ca_sds.yaml
  - name: authzproxy-config
    files:
      - config.yaml=authorization-proxy/config.yaml

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: authzproxy-sia
      fieldpath: data.SERVICEACCOUNT
    targets:
      - select:
          version: v1
          kind: ServiceAccount
          name: authzproxy-serviceaccount
        fieldPaths:
          - metadata.name
        options:
          create: true
      - select:
          version: v1
          kind: Deployment
          name: authzproxy-deployment
        fieldPaths:
          - spec.template.spec.serviceAccountName
        options:
          create: true
