---
apiVersion: v1
kind: Service
metadata:
  name: authzproxy
  labels:
    app: authzproxy-service
spec:
  type: ClusterIP
  selector:
    app: authzproxy-deployment
  ports:
    - name: https
      port: 443
      targetPort: https
