# athenz-identityprovider
---
admin:
  access_log:
    - name: access_log_file
      typed_config:
        "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
        path: "/dev/stdout"
  address:
    socket_address:
      address: 127.0.0.1
      port_value: 9901
node:
  id: envoy-0
  cluster: envoy-cluster
static_resources:
  listeners:
    - name: localhost_listener
      address:
        socket_address:
          protocol: TCP
          address: ::FFFF:127.0.0.1
          ipv4_compat: true
          port_value: 8080
      filter_chains: &localhost_filter_chains
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: localhost_proxy_prefix
                access_log: &access_log
                  - name: envoy.access_loggers.stdout
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                route_config: &localhost_route_config
                  name: localhost_proxy_route
                  virtual_hosts:
                    - name: localhost_proxy_hosts
                      domains:
                        # Only a single wildcard domain is permitted in route https_proxy_route
                        - "*"
                      typed_per_filter_config:
                        envoy.filters.http.ext_authz:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthzPerRoute
                          check_settings:
                            context_extensions:
                              virtual_host: localhost_proxy_hosts
                      routes: &localhost_routes
                        - match:
                            path_separated_prefix: "/status"
                          direct_response:
                            status: 200
                            body:
                              inline_string: "This is identity provider proxy."
                          response_headers_to_add:
                            - header:
                                key: x-athenz-action
                                value: "%REQ(:METHOD)%"
                            - header:
                                key: x-athenz-resource
                                value: "%REQ(:PATH)%"
                        - match:
                            path_separated_prefix: "/zms/v1"
                          route:
                            cluster: zms
                        - match:
                            path_separated_prefix: "/zts/v1"
                          route:
                            cluster: zts
                        - match:
                            prefix: "/health"
                          route:
                            cluster: opa
                        - match:
                            prefix: "/v1/data"
                          route:
                            cluster: opa
                        - match:
                            prefix: "/v0/data/identityprovider"
                          route:
                            cluster: opa
                        - match:
                            prefix: "/"
                          route:
                            cluster: envoy_admin
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
    #- name: localhost_listener_v4
    #  address:
    #    socket_address:
    #      protocol: TCP
    #      address: 127.0.0.1
    #      port_value: 8080
    #  filter_chains: *localhost_filter_chains
    #- name: localhost_listener_v6
    #  address:
    #    socket_address:
    #      protocol: TCP
    #      address: ::1
    #      port_value: 8080
    #  filter_chains: *localhost_filter_chains
    - name: https_listener
      address:
        socket_address:
          protocol: TCP
          address: ::FFFF:0.0.0.0
          ipv4_compat: true
          port_value: 443
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: https_proxy_prefix
                access_log: *access_log
                route_config:
                  name: https_proxy_route
                  virtual_hosts:
                    - name: https_proxy_hosts
                      domains:
                        # Only a single wildcard domain is permitted in route https_proxy_route
                        - "*"
                      routes:
                        - match:
                            prefix: "/health"
                          route:
                            cluster: opa
                        - match:
                            prefix: "/v1/data"
                          route:
                            cluster: opa
                        - match:
                            prefix: "/v0/data/identityprovider"
                          route:
                            cluster: opa
                http_filters:
                  - name: envoy.filters.http.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
          transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs: &tls_certificate_sds_secret_configs_identity
                  - name: identity_sds
                    sds_config:
                      path: /etc/envoy/identity_sds.yaml
                      resource_api_version: V3
  clusters:
    - name: envoy_admin
      connect_timeout: 0.25s
      type: STATIC # LOGICAL_DNS or STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: envoy_admin
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 9901
    - name: envoy_localhost
      connect_timeout: 0.25s
      type: STATIC # LOGICAL_DNS or STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: envoy_localhost
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8080
    - name: zms
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: zms
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: athenz-zms-server.athenz
                      port_value: 4443
      transport_socket: &transport_socket
        name: envoy.transport_sockets.tls
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
          common_tls_context:
            tls_certificate_sds_secret_configs: &tls_certificate_sds_secret_configs_role
              - name: role_sds
                sds_config:
                  path: /etc/envoy/role_sds.yaml
                  resource_api_version: V3
            validation_context_sds_secret_config: &validation_context_sds_secret_config_ca
              name: ca_sds
              sds_config:
                path: /etc/envoy/ca_sds.yaml
                resource_api_version: V3
    - name: zts
      connect_timeout: 0.25s
      type: LOGICAL_DNS
      dns_lookup_family: V4_ONLY
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: zts
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: athenz-zts-server.athenz
                      port_value: 4443
      transport_socket: *transport_socket
    - name: opa
      connect_timeout: 0.25s
      type: STATIC # LOGICAL_DNS or STATIC
      lb_policy: ROUND_ROBIN
      load_assignment:
        cluster_name: opa
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: 127.0.0.1
                      port_value: 8181
