---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: athenz-zts-server
  labels:
    app.kubernetes.io/name: athenz-zts-server
    app.kubernetes.io/instance: athenz-zts-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: athenz-zts-server
      app.kubernetes.io/instance: athenz-zts-server
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: athenz-zts-server
        app.kubernetes.io/instance: athenz-zts-server
    spec:
      restartPolicy: Always
      dnsPolicy: "ClusterFirst"
      volumes:
        - name: athenz-zts-cert-stores
          secret:
            secretName: athenz-zts-cert-stores
            defaultMode: 0555
            items:
              - key: zts_keystore.pkcs12
                path: zts_keystore.pkcs12
              - key: zts_truststore.jks
                path: zts_truststore.jks
              - key: zts_signer_keystore.pkcs12
                path: zts_signer_keystore.pkcs12
              - key: zms_client_keystore.pkcs12
                path: zms_client_keystore.pkcs12
              - key: zms_client_truststore.jks
                path: zms_client_truststore.jks
        - name: athenz-zts-keys
          secret:
            secretName: athenz-zts-keys
            defaultMode: 0555
            items:
              - key: zts.private.pem
                path: zts.private.pem
              - key: zts.public.pem
                path: zts.public.pem
        - name: athenz-admin-keys
          secret:
            secretName: athenz-admin-keys
            defaultMode: 0555
            items:
              - key: athenz_admin.cert.pem
                path: athenz_admin.cert.pem
              - key: athenz_admin.private.pem
                path: athenz_admin.private.pem
        - name: athenz-zts-conf
          configMap:
            name: athenz-zts-conf
        - name: athenz-plugins
          configMap:
            name: athenz-plugins
        - name: athenz-cacert
          configMap:
            name: athenz-cacert
            items:
              - key: ca.cert.pem
                path: ca-certificates.crt
        - name: athenz-conf
          emptyDir: {}
      initContainers:
        - name: zms-cli
          image: &athenz-cli-image ghcr.io/ctyano/athenz-cli:latest
          imagePullPolicy: &athenz-cli-imagePullPolicy IfNotPresent
          env: &athenz-cli-env
            - name: TZ
              value: Asia/Tokyo
          command: ["/bin/sh", "-c"]
          args:
            - |
              zms-cli \
                -key /athenz/admin/athenz_admin.private.pem \
                -cert /athenz/admin/athenz_admin.cert.pem \
                -c /etc/ssl/certs/ca-certificates.crt \
                -z https://athenz-zms-server:4443/zms/v1 \
                -d sys.auth \
                show-service zts \
              && \
              zms-cli \
                -key /athenz/admin/athenz_admin.private.pem \
                -cert /athenz/admin/athenz_admin.cert.pem \
                -c /etc/ssl/certs/ca-certificates.crt \
                -z https://athenz-zms-server:4443/zms/v1 \
                -d sys.auth \
                add-public-key zts "0" /athenz/zts/zts.public.pem \
              || \
              zms-cli \
                -key /athenz/admin/athenz_admin.private.pem \
                -cert /athenz/admin/athenz_admin.cert.pem \
                -c /etc/ssl/certs/ca-certificates.crt \
                -z https://athenz-zms-server:4443/zms/v1 \
                -d sys.auth \
                add-service zts "0" /athenz/zts/zts.public.pem
          resources:
            limits:
              memory: 32Mi
              cpu: 100m
            requests:
              memory: 16Mi
              cpu: 50m
          volumeMounts:
            - name: athenz-admin-keys
              mountPath: /athenz/admin
              readOnly: true
            - name: athenz-zts-keys
              mountPath: /athenz/zts
              readOnly: true
            - name: athenz-cacert
              mountPath: /etc/ssl/certs
              readOnly: true
        - name: athenz-conf
          image: *athenz-cli-image
          imagePullPolicy: *athenz-cli-imagePullPolicy
          env: *athenz-cli-env
          command: ["/bin/sh", "-c"]
          args:
            - |
              athenz-conf \
                -svc-key-file /athenz/admin/athenz_admin.private.pem \
                -svc-cert-file /athenz/admin/athenz_admin.cert.pem \
                -z https://athenz-zms-server:4443/zms/v1 \
                -t https://athenz-zms-server:4443/zts/v1 \
                -o /athenz/conf/athenz.conf
          resources:
            limits:
              memory: 32Mi
              cpu: 100m
            requests:
              memory: 16Mi
              cpu: 50m
          volumeMounts:
            - name: athenz-admin-keys
              mountPath: /athenz/admin
              readOnly: true
            - name: athenz-conf
              mountPath: /athenz/conf
            - name: athenz-cacert
              mountPath: /etc/ssl/certs
              readOnly: true
      containers:
        - name: athenz-zts-server
          image: ghcr.io/ctyano/athenz-zts-server:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Tokyo
            - name: ROOT
              value: /opt/athenz/zts
            - name: CLASSPATH
              value: /opt/athenz/zts/lib/jars/*
            - name: CONF_PATH
              value: /opt/athenz/zts/conf/zts_server
            - name: JAVA_OPTS
              value: "-Dathenz.root_dir=/opt/athenz/zts -Dathenz.jetty_home=/opt/athenz/zts -Dathenz.access_log_dir=/opt/athenz/zts/logs"
            - name: USER_CLASSPATH
              value: /usr/lib/jars/*
            - name: ZTS_STOP_TIMEOUT
              value: "30"
          ports:
            - name: https
              containerPort: 4443
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 17
            exec:
              command:
                - curl
                - -s
                - --fail
                - --resolve
                - athenz-zts-server:4443:127.0.0.1
                - https://athenz-zts-server:4443/zts/v1/status
          livenessProbe:
            initialDelaySeconds: 150
            periodSeconds: 10
            failureThreshold: 3
            exec:
              command:
                - curl
                - -s
                - --fail
                - --resolve
                - athenz-zts-server:4443:127.0.0.1
                - https://athenz-zts-server:4443/zts/v1/status
          resources:
            limits:
              memory: 2Gi
              cpu: 2
            requests:
              memory: 100Mi
              cpu: 200m
          volumeMounts:
            - name: athenz-zts-conf
              mountPath: /opt/athenz/zts/conf/zts_server
              readOnly: true
            - name: athenz-zts-keys
              mountPath: /opt/athenz/zts/var/keys
              readOnly: true
            - name: athenz-conf
              mountPath: /opt/athenz/zts/conf/athenz
              readOnly: true
            - name: athenz-zts-cert-stores
              mountPath: /opt/athenz/zts/var/certs
              readOnly: true
            - name: athenz-plugins
              mountPath: /athenz/plugins
            - name: athenz-cacert
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca-certificates.crt
              readOnly: true
