---
apiVersion: v1
kind: Service
metadata:
  name: authorizer
  labels:
    app: authorizer-service
spec:
  type: ClusterIP
  selector:
    app: authorizer-deployment
  ports:
    - name: grpc
      port: 9191
      targetPort: grpc
