---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: identityprovider-list-nodes
subjects:
  - kind: User
    name: system:anonymous
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    namespace: athenz
    name: identityprovider
roleRef:
  kind: ClusterRole
  name: identityprovider-list-nodes
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: identityprovider-list-pods
subjects:
  - kind: ServiceAccount
    namespace: athenz
    name: identityprovider
roleRef:
  kind: ClusterRole
  name: identityprovider-list-pods
  apiGroup: rbac.authorization.k8s.io
