---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identityprovider-list-nodes
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: identityprovider-list-pods
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
      - watch
