---
apiVersion: v1
kind: Service
metadata:
  name: identityprovider
  labels:
    app: identityprovider-service
spec:
  type: ClusterIP
  selector:
    app: identityprovider-deployment
  ports:
    - name: https
      port: 443
      targetPort: https
