apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
- deployment.yaml
- namespace.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- files:
  - zms.private.pem=keys/zms.private.pem
  name: athenz-zms-keys
  type: Opaque
- files:
  - zms.cert.pem=certs/zms.cert.pem
  name: athenz-zms-certs
  type: Opaque
- files:
  - ca.cert.pem=certs/ca.cert.pem
  name: athenz-cacert
  type: Opaque

configMapGenerator:
- files:
  - athenz.properties=conf/athenz.properties
  - zms.properties=conf/zms.properties
  - authorized_client_ids.txt=conf/authorized_client_ids.txt
  - authorized_services.json=conf/authorized_services.json
  - logback.xml=conf/logback.xml
  - solution_templates.json=conf/solution_templates.json
  name: athenz-zms-conf
images:
- name: ghcr.io/ctyano/athenz-plugins:latest
  newName: ghcr.io/ctyano/athenz-plugins
  newTag: latest
- name: ghcr.io/ctyano/athenz-zms-server:latest
  newName: ghcr.io/ctyano/athenz-zms-server
  newTag: latest
