---
apiVersion: v1
kind: Service
metadata:
  name: authzwebhook
  labels:
    app: authzwebhook-service
spec:
  type: ClusterIP
  selector:
    app: authzwebhook-deployment
  ports:
    - name: https
      port: 443
      targetPort: https
    - name: mtls
      port: 4443
      targetPort: mtls
