---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - deployment.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: authorizer-sia
    envs:
      - athenz-sia/athenz-sia.env
  - name: authorizer-envoy
    files:
      - config.yaml=envoy/config.yaml
      - identity_sds.yaml=envoy/identity_sds.yaml
      - role_sds.yaml=envoy/role_sds.yaml
      - ca_sds.yaml=envoy/ca_sds.yaml
  - name: athenz-authorizer
    envs:
      - athenz-authorizer/athenz-authorizer.env
  - name: authorizer-config
    files:
      - config.yaml=athenz-authorizer/config.yaml
  - name: authorizer-policy
    files:
      - system.authz.rego=athenz-authorizer/policy/system.authz.rego
      - system.log.rego=athenz-authorizer/policy/system.log.rego
#  - name: athenz-cacert
#    files:
#      - ca.cert.pem=certs/ca.cert.pem

replacements:
  - source:
      version: v1
      kind: ConfigMap
      name: authorizer-sia
      fieldpath: data.SERVICEACCOUNT
    targets:
      - select:
          version: v1
          kind: ServiceAccount
          name: authorizer-serviceaccount
        fieldPaths:
          - metadata.name
        options:
          create: true
      - select:
          version: v1
          kind: Deployment
          name: authorizer-deployment
        fieldPaths:
          - spec.template.spec.serviceAccountName
        options:
          create: true
