---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authorizer-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: authorizer-role
subjects:
  - kind: ServiceAccount
    namespace: athenz
    name: authorizer
