---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: client-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: client-role
subjects:
  - kind: ServiceAccount
    namespace: athenz
    name: client
