---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: client-role
rules:
  - apiGroups:
      - ""
    resourceNames:
      - client-tls
    resources:
      - secrets
    verbs:
      - get
      - patch
      - create
