---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client-service
spec:
  type: ClusterIP
  selector:
    app: client-deployment
  ports:
    - name: https
      port: 443
      targetPort: https
