---
apiVersion: v1
kind: Service
metadata:
  name: client
  labels:
    app: client-service
spec:
  type: ClusterIP
  selector:
    app: client-deployment
  ports:
    - name: http
      port: 80
      targetPort: http
