apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

generatorOptions:
  disableNameSuffixHash: true

resources:
- namespace.yaml
- service.yaml
- statefulset.yaml

configMapGenerator:
images:
- name: ghcr.io/ctyano/athenz-db:latest
  newName: ghcr.io/ctyano/athenz-db
  newTag: latest
