---
apiVersion: v1
kind: Pod
metadata:
  name: vegeta
  labels:
    app: vegeta
spec:
  restartPolicy: Never
  volumes:
    - name: athenz-cacert
      configMap:
        name: athenz-cacert
        items:
          - key: ca.cert.pem
            path: ca-certificates.crt
  containers:
    - name: vegeta
      image: ghcr.io/ctyano/docker-vegeta:latest
      imagePullPolicy: IfNotPresent
      command:
        - tail
        - -f
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
      volumeMounts:
        - name: athenz-cacert
          mountPath: /etc/ssl/certs/ca-certificates.crt
          subPath: ca-certificates.crt
          readOnly: true
