---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: athenz

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: athenz-ui-keys
    type: Opaque
    files:
      - ui.private.pem=keys/ui.private.pem
      - ui.public.pem=keys/ui.public.pem
      - ui.cert.pem=certs/ui.cert.pem
  - name: athenz-admin-keys
    type: Opaque
    files:
      - athenz_admin.private.pem=keys/athenz_admin.private.pem
      - athenz_admin.cert.pem=certs/athenz_admin.cert.pem

configMapGenerator:
  - name: athenz-ui-config
    files:
      - extended-config.js=config/extended-config.js
  - name: athenz-cacert
    files:
      - ca.cert.pem=certs/ca.cert.pem
